### ISSUE TITLE
Need Grand Total Hour Watcher & Reporter

### ISSUE THREAD

**Issue by steve-erickson** [jeffmiranda/StudentCentre#33]
Every time the "GRAND TOTAL OF ALL HOURS" value is incremented we need to report it.  Like this:
Let's say Catrina has 549 GRAND TOTAL OF ALL HOURS (includes coloured belt hours + ITP hours + weapons hours).  Then on Wednesday, she practices and we increment it to 550.  The Grand Total Hours Watcher & Reporter needs to show:
Catrina Fleming ... Grand Total Hours ... 550

There are two different criteria for reporting:
A) For hours up to and including 1000 - Interval = 50
B) For hours greater than 1000 - Interval = 100

When the Water & Reporter creates a  new record (for Catrina, for example) I need to be able to flag it as having been dealt with.  Essentially, once the system reports that Catrina has increments past 550 Grand Total Hours, I will create a certificate.  I need to able to flag this as having been done.  Kinda like we have an active and inactive flag now ... If the grid that shows these Grand Total Hour increments also had a switch so that I could set it to show either Active or Inactive, that might be good.  That way, when I've created the certificates, I could just toggle the active status.

Make sense?

**Comment by jeffmiranda** [comment]
Wow! You first posted this back in August! It's all done now! :)
