### ISSUE TITLE
Class list box on TAKE ATTENDANCE dos not "page"

### ISSUE THREAD

**Issue by steve-erickson** [jeffmiranda/StudentCentre#44]
Hey Jeff
I recently added a couple more scheduled classes and then discovered my "youth ..." classes no longer appeared in the list (on take attendance).  When I made these new scheduled classes inactive (they were just camp classes needed for last weekend), my "youth ..." classes reappeared.  I think there were just too many classes for the list and this control isn't set up to "page".  
Can you add paging to this control?

**Comment by steve-erickson** [comment]
Hey Jeff
Do you think you could fix this soon?
We have so many classes now, I constantly have to toggle some off to see others :-)

**Comment by steve-erickson** [comment]
It's not just on TAKE ATTENDANCE ... Anywhere the class list box is shown, it's missing the paging ...

**Comment by jeffmiranda** [comment]
Try it now!


*Jeff Miranda**ph.* 403 836 3338  |  *fx.* 403 775 4342
www.jeffmiranda.com

*Save our in-boxes! www.emailcharter.org <http://www.emailcharter.org>*

**Comment by steve-erickson** [comment]
Fixed! 

Thanks! 

Meet next week :-) ? 

---
Thanks, Steve

On 2016-03-01 10:57, Jeff Miranda wrote: 

> Try it now!
> 
> *Jeff Miranda**ph.* 403 836 3338 | *fx.* 403 775 4342
> www.jeffmiranda.com
> 
> *Save our in-boxes! www.emailcharter.org <http://www.emailcharter.org>*
> 
> On Thu, Feb 25, 2016 at 9:24 AM, steve-erickson <notifications@github.com>
> wrote:
> 
>> It's not just on TAKE ATTENDANCE ... Anywhere the class list box is shown,
>> it's missing the paging ...
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jeffmiranda/StudentCentre/issues/44#issuecomment-188862268>
>> .
>> 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/jeffmiranda/StudentCentre/issues/44#issuecomment-190851727

**Comment by steve-erickson** [comment]
All good!
