### ISSUE TITLE
Active student not appearing in class list

### ISSUE THREAD

**Issue by steve-erickson** [jeffmiranda/StudentCentre#51]
Hey Jeff
Joseph (Jeff) Vea is active and enrolled in the adult class but doesn't appear in the adult class list?
![image](https://cloud.githubusercontent.com/assets/8173522/5379078/c27b9f3e-804b-11e4-96cb-5126fa068b2e.png)

**Comment by jeffmiranda** [comment]
Is this still outstanding Steve?

**Comment by steve-erickson** [comment]
He was enrolled when the system went live initially.
And never attended a class.
Let's close this issue because I think the problem that was causing it was fixed, it's just that this student didn't get sorted out as he never attended a class.
