### ISSUE TITLE
Weapons ITP certificates not creating

### ISSUE THREAD

**Issue by steve-erickson** [jeffmiranda/StudentCentre#55]
![image](https://cloud.githubusercontent.com/assets/8173522/5383856/0d4518d0-8072-11e4-904e-99af601afc68.png)

**Comment by jeffmiranda** [comment]
Okay, all the templates should be up on the website now.

I also updated the anniversary certificate functionality. Now the system will only create an anniversary certificate if a given date is within falls within a range of days from the student's anniversary. The range can be specified in the System Settings. The default is 30 days. The maximum is 180 days.
