### ISSUE TITLE
Level certificates should NOT have date

### ISSUE THREAD

**Issue by steve-erickson** [jeffmiranda/StudentCentre#58]
Hey Jeff
Spent a couple hours yesterday going through the new certificates and even awarded some to kids.  The kids LOVE them!
One thing I noticed though was the leveling certificates are dated.  This date must be the date the student reaches the threshold.  It will almost never correspond to the actual date the student passes their test however so it's almost always going to be wrong.  
Can you please REMOVE the DATE on all leveling certificates?
Thanks!

**Comment by jeffmiranda** [comment]
Done!
