### ISSUE TITLE
Steve messed up the Ranking page

### ISSUE THREAD

**Issue by steve-erickson** [jeffmiranda/StudentCentre#64]
Hey Jeff
I added some info to the Ranking page and I can't seem to get the title "Testing" to look like the rest of the titles on the page (other than the top "Ranking" title, all others are set to Heading 2 but I can't seem to get the "Testing" text to look like the others even though I set it to Heading 2.
Can you fix it?
Thanks, Steve

**Comment by jeffmiranda** [comment]
Fixed! There was a <span> tag that was messing things up :(

**Comment by steve-erickson** [comment]
Thanks, Jeff!

Steve
