### ISSUE TITLE
Journal record reactivation

### ISSUE THREAD

**Issue by steve-erickson** [jeffmiranda/StudentCentre#78]
Hey Jeff

I think the comment that gets inserted when a record gets reactivated is getting added too often.  Almost all of my records have this comment now.  Even ones that were reactivated a while ago ...

**Comment by jeffmiranda** [comment]
This was fixed in commit SHA: 907b585. Please test it out.

**Comment by steve-erickson** [comment]
Haven't seen this issue any more :-)
