### ISSUE TITLE
Testing Journal Date needs to be clearable :-)

### ISSUE THREAD

**Issue by steve-erickson** [jeffmiranda/StudentCentre#79]
I know that's not a word :-)

**Comment by steve-erickson** [comment]
Hey Jeff
Do you think this is something you could fix soon?
Making the testing date in the Journal something I can remove when necessary?

**Comment by jeffmiranda** [comment]
Done! Try it out please :)

**Comment by steve-erickson** [comment]
Jeff is back!!!!!!!!!!!!!!

Works awesome Jeff, thanks!!!!!!

What's next??????????

Steve Sensei
www.BigRock-Aikikai.com
