### ISSUE TITLE
When generating large batches of certificates the user is directed to a 404 error page

### ISSUE THREAD

**Issue by jeffmiranda** [jeffmiranda/StudentCentre#80]
Large batches of certificates results in an error. Not entirely sure why but it seems that the server has a limit to the size of ZIP file that can be generated. Workaround could be limiting the number of certificates that can be selected. say perhaps 50? Thoughts?

**Comment by steve-erickson** [comment]
Ok Jeff.  I'll limit the number of certs I run.  Thanks for looking into it. 

Steve Sensei
www.BigRock-Aikikai.com

**Comment by jeffmiranda** [comment]
Do you want me to build in a limit? For example, you can only batch a
maximum of 50 certificates?

*Jeff Miranda*
*Web & Graphic Designer*
Ph. 403 836 3338
LinkedIn <https://www.linkedin.com/in/jeff-miranda-0b404921> | Twitter
<https://twitter.com/jeffmdesigns>
jeffmiranda.com <http://www.jeffmiranda.com>

*Save our in-boxes! emailcharter.org <http://www.emailcharter.org>*

1. Where's the Any key? <https://goo.gl/T78dmP>
2. Jeff, get off the internet! I need to use the phone!
<https://goo.gl/GdTn9u>

**Comment by steve-erickson** [comment]
No, don't worry about adding a limit.  I will just build them in smaller batches :-)
Thanks for all your help!

**Comment by steve-erickson** [comment]
Not necessary ... We got more important things for you to spend your time on :-)

Steve Sensei
www.BigRock-Aikikai.com
